##version: '3.8'
#
#services:
#  app-database:
#    image: mysql:9.1
#    container_name: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    env_file:
#      - .env
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#    networks:
#        - app-network
#
#  app-database-ihm:
#    image: adminer:4.8.1-standalone
#    container_name: mysql-ihm
#    restart: always
#    #ports:
#      #- 8080:8080
#
#    networks:
#          - app-network
#
#  my-spring-boot-app:
#    image: gestionclients # Nom de l'image Docker que vous avez construite
#    build:
#      context: .
#    env_file:
#      - .env # Ce fichier contient les variables d'environnement
#    ports:
#      - "8080:8080" # Map le port 8080 du container vers le port 8080 de votre machine hôte
#    networks:
#      - app-network
#
#networks:
#  app-network:
#    external: true
#    name: app-network
#    driver: bridge
